apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: aman-devsecops-deploy
  namespace: aman-devsecops-project
  labels:  
    app: aman-devsecops-project  
spec:  
  replicas: 2  
  selector:  
    matchLabels:  
      app: aman-devsecops-project  
  template:  
    metadata:  
      labels:  
        app: aman-devsecops-project  
    spec:  
      topologySpreadConstraints:  
        - maxSkew: 1  
          topologyKey: topology.kubernetes.io/zone  
          whenUnsatisfiable: DoNotSchedule  
          labelSelector:  
            matchLabels:  
              app: aman-devsecops-project  
      containers:  
        - name: aman-devsecops-container  
          image: 185137893823.dkr.ecr.ap-south-1.amazonaws.com/devsecops-project-ecr:latest  
          ports:  
            - containerPort: 8080  

---
apiVersion: v1  
kind: Service  
metadata:  
  name: aman-devsecops-project-svc  
  namespace: aman-devsecops-project
  labels:  
    app: aman-devsecops-project  
spec:  
  type: NodePort  
  selector:  
    app: aman-devsecops-project  
  ports:  
    - port: 80  
      targetPort: 8080  
      protocol: TCP  
      nodePort: 31000  